{
 "title": "Number of calls to endpoints practica",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of calls to server in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total) - sum(min_over_time(server_requests_total [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to bye endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bye_requests_total) - sum(min_over_time(bye_requests_total [1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to main endpoint in last hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total) - sum(min_over_time(main_requests_total[1h]))"
    }
   ]
  },
  {
   "title": "Number of calls to healthcheck endpoint in the last hour",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "healthcheck_requests_total - min_over_time(healthcheck_requests_total [1h])"
    }
   ]
  },
  {
   "title": "Memory usage vs Memory requests namespace",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes) by (pod)",
     "legendFormat": "{{ pod }} memory usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)",
     "legendFormat": "{{pod }} memory requests"
    }
   ]
  },
  {
   "title": "Memory usage vs Memory requests by pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes {pod=\"$pod\"}) ",
     "legendFormat": "{{ pod }} memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", pod=\"$pod\"}) ",
     "legendFormat": "{{pod }} memory requests"
    }
   ]
  }
 ]
}