apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec: 
      containers: 
      - name: web
        image: fblanco86/simple-server:0.0.1
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP
          - name: metrics
            containerPort: 8000
            protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 200m
          limits:
            memory: 64Mi
            cpu: 500m       
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 20
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP 
  selector:
    app: web
  ports: 
  - protocol: TCP
    port: 8081
    targetPort: 8081 
    name: http
  - protocol: TCP
    port: 8000
    targetPort: 8000     
    name: metrics